// ============================================================
// backend/config/curriculumMap.js
// EXACT topic-specific lesson titles per roadmap module.
// These replace generic stubs. Every title is a precise topic.
// ============================================================
'use strict';

// Format: roadmapTitle -> [moduleTitle -> [lesson titles]]
// Must match existing module titles in DB exactly (case-insensitive compare).
const CURRICULUM_MAP = {

  'Python': {
    'Python Interpreter & Setup':       ['Python Installation & Environment Setup','How the CPython Interpreter Works','Running Python Scripts from Terminal'],
    'Variables & Core Data Types':      ['Integers, Floats & Numeric Types','Strings & String Methods','Booleans, None & Type Casting'],
    'Control Flow & Branching':         ['if / elif / else Statements','Comparison & Logical Operators','Nested Conditionals & Short-Circuit Evaluation'],
    'Loops & Iteration':                ['for Loops & range()','while Loops & Loop Control','List Comprehensions & Generator Expressions'],
    'Functions & Scope':                ['Defining Functions & Parameters','*args, **kwargs & Default Arguments','Closures, Scope & LEGB Rule'],
    'Lists & Tuples':                   ['List Operations & Slicing','Tuple Immutability & Packing','Sorting, Searching & List Methods'],
    'Dictionaries & Sets':              ['Dictionary Creation, Access & Methods','Set Operations: Union, Intersection, Difference','Dictionary Comprehensions & Nested Dicts'],
    'File Handling & I/O':              ['Reading & Writing Text Files','Working with CSV & JSON Files','Context Managers & the with Statement'],
    'Object Oriented Python':           ['Classes, Objects & __init__','Inheritance & Method Overriding','Dunder Methods & Operator Overloading'],
    'Modules & Packages':               ['Importing Standard Library Modules','Creating Custom Packages with __init__.py','Virtual Environments & pip'],
    'Exception Handling':               ['try / except / finally Blocks','Raising Custom Exceptions','Logging Errors with the logging Module'],
    'Database Integration':             ['SQLite3 with Python','SQLAlchemy ORM Basics','PostgreSQL with psycopg2'],
  },

  'JavaScript': {
    'JS Fundamentals':                  ['Variables: var, let & const','Data Types & Type Coercion','Operators & Expressions'],
    'Control Flow':                     ['if/else & Switch Statements','for, while & do-while Loops','break, continue & Labeled Statements'],
    'Functions':                        ['Function Declarations vs Expressions','Arrow Functions & Lexical this','Higher-Order Functions & Callbacks'],
    'Scope & Closures':                 ['Global vs Local Scope','Closures & the Closure Trap','IIFE Pattern & Module Pattern'],
    'Arrays & Objects':                 ['Array Methods: map, filter, reduce','Object Literals & Destructuring','Spread & Rest Operators'],
    'Asynchronous JS':                  ['Callbacks & Callback Hell','Promises & Promise Chaining','async/await & Error Handling'],
    'DOM Manipulation':                 ['Selecting & Modifying DOM Elements','Event Listeners & Event Delegation','Creating & Removing DOM Nodes'],
    'ES6+ Features':                    ['Template Literals & Tagged Templates','Modules: import & export','Optional Chaining & Nullish Coalescing'],
    'Error Handling & Debugging':       ['try/catch/finally in JS','Custom Error Classes','Debugging with Chrome DevTools'],
    'Web APIs':                         ['Fetch API & HTTP Requests','LocalStorage & SessionStorage','Web Workers & Background Threads'],
    'Functional Programming':           ['Pure Functions & Immutability','Function Composition & Currying','Memoization & Lazy Evaluation'],
    'JavaScript Performance':           ['Event Loop & Call Stack','Memory Leaks & Garbage Collection','Code Splitting & Lazy Loading'],
  },

  'TypeScript': {
    'TypeScript Setup':                 ['Installing TypeScript & tsconfig.json','TypeScript Compiler Options','Running TS with ts-node'],
    'Type System Basics':               ['Primitive Types & Type Annotations','Union & Intersection Types','Literal Types & Type Narrowing'],
    'Functions in TypeScript':          ['Typed Function Signatures','Optional & Default Parameters','Function Overloads'],
    'Interfaces & Type Aliases':        ['Defining Interfaces','Type Aliases vs Interfaces','Extending & Implementing Interfaces'],
    'Classes in TypeScript':            ['Classes, Constructors & Access Modifiers','Abstract Classes & Abstract Methods','Mixins in TypeScript'],
    'Generics':                         ['Generic Functions & Generic Interfaces','Generic Constraints with extends','Utility Types: Partial, Required, Pick, Omit'],
    'Advanced Types':                   ['Mapped Types','Conditional Types & infer','Template Literal Types'],
    'Enums & Decorators':               ['Numeric & String Enums','Const Enums & Ambient Enums','Class & Method Decorators'],
    'Modules & Namespaces':             ['ES Module Syntax in TS','Declaration Files (.d.ts)','Path Aliases in tsconfig'],
    'TypeScript with React':            ['Typing React Props & State','Typing Hooks: useState, useRef, useReducer','Typing Event Handlers & Refs'],
    'TypeScript with Node.js':          ['Typing Express Middleware','Typing Mongoose Models','Typing Environment Variables'],
    'Error Handling & Strict Mode':     ['strict Mode & noImplicitAny','Discriminated Unions for Error Types','never Type & Exhaustive Checks'],
  },

  'Java': {
    'Java Environment':                 ['Installing JDK & Configuring JAVA_HOME','Compiling & Running Java Programs','Maven & Gradle Build Tools'],
    'Core Java Syntax':                 ['Primitive Types & Wrapper Classes','Operators, Expressions & Casting','String Class & StringBuilder'],
    'Control Flow':                     ['if/else, Switch & Ternary Operator','for, while & Enhanced for Loop','break, continue & Labeled Loops'],
    'Object Oriented Java':             ['Classes, Objects & Constructors','Inheritance, super & Method Overriding','Polymorphism & Dynamic Dispatch'],
    'Interfaces & Abstraction':         ['Interfaces & Default Methods','Abstract Classes vs Interfaces','Functional Interfaces & Lambda Expressions'],
    'Collections Framework':            ['ArrayList, LinkedList & Stack','HashMap, LinkedHashMap & TreeMap','HashSet, TreeSet & Priority Queue'],
    'Generics':                         ['Generic Classes & Methods','Bounded Type Parameters','Wildcards in Generics'],
    'Exception Handling':               ['Checked vs Unchecked Exceptions','try-catch-finally & Multi-catch','Custom Exceptions & throws'],
    'Java Streams & Lambdas':           ['Stream API: filter, map, collect','Reduction Operations: reduce, count, sum','Optional Class & orElse'],
    'Concurrency':                      ['Threads & Runnable Interface','synchronized Keyword & Locks','ExecutorService & Thread Pools'],
    'File I/O':                         ['Reading Files with BufferedReader','Writing Files with FileWriter','Java NIO & Path API'],
    'Java Database Connectivity':       ['JDBC Setup & Connection','Prepared Statements & ResultSet','JPA & Hibernate ORM Basics'],
  },

  'C Programming': {
    'C Environment':                    ['GCC Compiler & Makefile Basics','C Program Structure: main(), Headers','Preprocessor Directives & Macros'],
    'Data Types & Variables':           ['Primitive Types: int, float, char, double','Variable Scope & Storage Classes','Constants & #define vs const'],
    'Operators & Expressions':          ['Arithmetic, Relational & Logical Operators','Bitwise Operators & Bit Manipulation','Precedence & Associativity'],
    'Control Flow':                     ['if/else & Switch-Case','for, while & do-while Loops','goto Statement & Loop Control'],
    'Functions':                        ['Function Declaration, Definition & Call','Pass by Value vs Pass by Reference','Recursive Functions'],
    'Arrays & Strings':                 ['One-Dimensional & Multi-Dimensional Arrays','String Handling: strcpy, strlen, strcmp','Character Arrays vs String Literals'],
    'Pointers':                         ['Pointer Basics: Declaration & Dereferencing','Pointer Arithmetic & Array Pointers','Pointers to Functions'],
    'Structures & Unions':              ['struct Definition & Nested Structs','union & Memory Sharing','Bit Fields in Structures'],
    'Dynamic Memory':                   ['malloc, calloc, realloc & free','Memory Leaks & Valgrind Basics','Implementing a Dynamic Array'],
    'File I/O':                         ['fopen, fclose, fread, fwrite','fprintf, fscanf & Text Files','Binary File Operations'],
    'Linked Lists':                     ['Singly Linked List: Insert & Delete','Doubly Linked List Implementation','Circular Linked List'],
    'Advanced C Concepts':              ['Function Pointers & Callbacks','Volatile & Restrict Qualifiers','C99/C11 Features: VLAs, _Bool'],
  },

  'C++': {
    'C++ Setup & Basics':               ['g++ Compiler, CMake & Namespaces','C++ vs C: Key Differences','Input/Output with cin & cout'],
    'OOP in C++':                       ['Classes, Objects & Access Specifiers','Constructors, Destructors & this','Inheritance & Virtual Functions'],
    'Memory Management':                ['Stack vs Heap Allocation','new & delete Operators','Smart Pointers: unique_ptr, shared_ptr'],
    'Templates':                        ['Function Templates','Class Templates','Template Specialization'],
    'STL Containers':                   ['vector, list & deque','map, unordered_map & set','stack, queue & priority_queue'],
    'STL Algorithms':                   ['sort, find & binary_search','transform, accumulate & copy','Custom Comparators & Predicates'],
    'Operator Overloading':             ['Arithmetic & Comparison Operators','Stream Operators << & >>','Assignment & Subscript Operators'],
    'Exception Handling':               ['try/catch & Standard Exceptions','Custom Exception Classes','RAII & Exception Safety'],
    'C++11/14/17 Features':             ['Lambda Expressions & Captures','Move Semantics & Rvalue References','constexpr, auto & decltype'],
    'Concurrency in C++':               ['std::thread & Joining Threads','Mutex, lock_guard & unique_lock','std::async & std::future'],
    'File I/O & Streams':               ['ifstream & ofstream','Stringstreams & Formatted I/O','Binary File Operations'],
    'Design Patterns in C++':           ['Singleton & Factory Pattern','Observer Pattern','CRTP & Policy-Based Design'],
  },

  'HTML': {
    'HTML Foundations':                 ['HTML Document Structure & DOCTYPE','Head Elements: meta, title, link','Body & Block vs Inline Elements'],
    'Text & Semantics':                 ['Headings h1-h6 & Paragraphs','Lists: ul, ol & dl','Semantic Elements: article, section, aside'],
    'Links & Media':                    ['Anchor Tags & href Attributes','Images: src, alt & Loading','Audio & Video Elements'],
    'Forms':                            ['Form Tag & Action/Method','Input Types: text, email, number, date','Select, Textarea & Datalist'],
    'Tables':                           ['Table Structure: thead, tbody, tfoot','Table Attributes: colspan, rowspan','Accessible Table Markup'],
    'HTML5 APIs':                       ['Canvas Element Basics','Geolocation API','Drag & Drop API'],
    'Accessibility':                    ['ARIA Roles & Attributes','Keyboard Navigation & Tab Order','Screen Reader Compatibility'],
    'SEO & Meta Tags':                  ['Open Graph Meta Tags','Structured Data with Schema.org','Canonical & Robots Meta Tags'],
    'HTML Templating':                  ['Template Element & Slots','Web Components Overview','Shadow DOM Basics'],
    'Forms Validation':                 ['required, minlength & pattern Attributes','Constraint Validation API','Custom Validation Messages'],
    'Embedded Content':                 ['iframe: Embedding External Content','SVG Inline Markup','MathML Basics'],
    'HTML Best Practices':              ['HTML Linting & Validation','Progressive Enhancement','Responsive Images with srcset & picture'],
  },

  'CSS': {
    'CSS Syntax & Selectors':           ['Type, Class & ID Selectors','Attribute Selectors & Pseudo-classes','Combinators: Descendant, Child, Sibling'],
    'Box Model':                        ['margin, border, padding & content','box-sizing: content-box vs border-box','Outline vs Border'],
    'Typography':                       ['font-family, font-size & font-weight','line-height, letter-spacing & text-align','Google Fonts & @font-face'],
    'Colors & Backgrounds':             ['Color Formats: HEX, RGB, HSL','Gradients: linear-gradient & radial-gradient','background-image & background Shorthand'],
    'Flexbox':                          ['display:flex & Flex Container Properties','flex-grow, flex-shrink & flex-basis','Aligning Items: align-items & justify-content'],
    'CSS Grid':                         ['grid-template-columns & grid-template-rows','grid-column & grid-row Placement','Auto-placement & grid-auto-flow'],
    'Responsive Design':                ['Media Queries & Breakpoints','Mobile-First vs Desktop-First','Responsive Units: %, vw, vh, rem'],
    'Transitions & Animations':         ['CSS transition Property','@keyframes & animation Property','Performance: transform & opacity Animations'],
    'CSS Variables':                    ['Declaring & Using Custom Properties','Theming with CSS Variables','Variable Fallbacks'],
    'Positioning & Z-index':            ['static, relative, absolute, fixed, sticky','z-index & Stacking Context','Centering Techniques'],
    'Pseudo-elements & Effects':        ['::before & ::after','text-shadow & box-shadow','filter & clip-path'],
    'CSS Architecture':                 ['BEM Naming Convention','SMACSS & OOCSS Principles','CSS Specificity & The Cascade'],
  },

  'React Developer': {
    'React Fundamentals':               ['create-react-app & Vite Setup','JSX Syntax & Transpilation','React Developer Tools'],
    'Components':                       ['Function Components vs Class Components','Props & PropTypes Validation','Component Composition & Children'],
    'State Management':                 ['useState Hook: Local State','Lifting State Up','State Batching & Immutability'],
    'Effects & Lifecycle':              ['useEffect: Mounting & Cleanup','Dependency Arrays in useEffect','useLayoutEffect vs useEffect'],
    'React Router':                     ['BrowserRouter & Route Setup','Nested Routes & Outlet','useNavigate & Link Component'],
    'Advanced Hooks':                   ['useContext & Context API','useReducer for Complex State','useMemo & useCallback Optimization'],
    'Forms in React':                   ['Controlled Components & onChange','Uncontrolled Components & useRef','Form Libraries: React Hook Form'],
    'API Integration':                  ['Fetching with useEffect & Axios','Loading & Error States','React Query for Data Fetching'],
    'Performance Optimization':         ['React.memo & Preventing Re-renders','Code Splitting with React.lazy','Profiling with React DevTools'],
    'Testing React':                    ['Jest Setup & Unit Testing','React Testing Library Queries','Mocking API Calls in Tests'],
    'State Management Libraries':       ['Redux Toolkit: Slices & Store','Zustand State Management','Context vs Redux Decision Guide'],
    'Production Build':                 ['Environment Variables in React','Deploying to Vercel & Netlify','Progressive Web App Setup'],
  },

  'Node.js Developer': {
    'Node.js Fundamentals':             ['Node.js Architecture & Event Loop','Installing Node & nvm','Running JS Scripts with Node'],
    'Core Modules':                     ['fs Module: Read, Write, Watch','path Module & Directory Operations','os & process Modules'],
    'NPM & Packages':                   ['package.json & package-lock.json','Installing, Updating & Removing Packages','Publishing a Package to npm'],
    'HTTP Module':                      ['Creating HTTP Server from Scratch','Handling Requests & Sending Responses','Routing without Framework'],
    'Express.js Basics':                ['Express Setup & Application Object','Routing: GET, POST, PUT, DELETE','Middleware: Built-in & Custom'],
    'Asynchronous Node.js':             ['Callbacks, Promises in Node','async/await in Node.js','EventEmitter Pattern'],
    'REST API Design':                  ['RESTful API Principles','Request Validation with Joi','Pagination & Filtering APIs'],
    'Authentication':                   ['JWT Authentication Flow','bcrypt Password Hashing','Refresh Tokens & Token Rotation'],
    'Database with Node.js':            ['MongoDB with Mongoose','PostgreSQL with Sequelize','Redis for Caching'],
    'Error Handling':                   ['Global Error Handler Middleware','Operational vs Programmer Errors','HTTP Status Codes Best Practices'],
    'Testing Node.js':                  ['Mocha & Chai Setup','Supertest for API Integration Testing','Mocking with Sinon'],
    'Deployment & DevOps':              ['PM2 Process Manager','Docker for Node.js Apps','CI/CD with GitHub Actions'],
  },

  'Express.js Developer': {
    'Express Setup':                    ['Installing Express & Project Structure','Application vs Router-level Middleware','Express Generator Scaffold'],
    'Routing':                          ['Route Parameters & Query Strings','Express Router & Modular Routes','Route Chaining & app.route()'],
    'Middleware':                       ['Understanding Middleware Stack','Body Parser & Cookie Parser','Morgan Logging Middleware'],
    'Request & Response':               ['req.params, req.query & req.body','res.json(), res.send() & res.render()','Setting Response Headers & Status Codes'],
    'Template Engines':                 ['EJS Template Syntax','Handlebars & Pug Overview','Passing Data to Views'],
    'Error Handling':                   ['Custom Error Middleware (4 params)','express-async-errors Package','Centralized Error Response Format'],
    'Authentication & Security':        ['Passport.js Local Strategy','express-session & Cookie Security','Helmet.js Security Headers'],
    'File Uploads':                     ['Multer for File Upload Handling','Validating File Types & Size','Storing Files on S3'],
    'Database Integration':             ['Mongoose with Express','Sequelize with Express','Connection Pooling Best Practices'],
    'Rate Limiting & CORS':             ['express-rate-limit Middleware','CORS Configuration','DDoS Protection Patterns'],
    'Testing Express APIs':             ['Supertest Integration Testing','Jest & Mock Dependencies','API Contract Testing'],
    'Production Express':               ['Compression & gzip Middleware','Cluster Mode & PM2','Express Performance Best Practices'],
  },

  'Next.js Developer': {
    'Next.js Fundamentals':             ['Pages Router vs App Router','File-based Routing','next.config.js Configuration'],
    'Data Fetching':                    ['getServerSideProps & getStaticProps','ISR: Incremental Static Regeneration','fetch in Server Components'],
    'App Router':                       ['layout.tsx & page.tsx Conventions','Server Components vs Client Components','Loading & Error Boundaries'],
    'Routing & Navigation':             ['Dynamic Routes & Catch-all Segments','Parallel & Intercepting Routes','Link Component & useRouter'],
    'API Routes':                       ['Creating API Route Handlers','Route Handlers in App Router','Middleware: next/server'],
    'Authentication':                   ['NextAuth.js Setup & Providers','Protecting Routes with Middleware','Session Management in Next.js'],
    'Styling':                          ['CSS Modules in Next.js','Tailwind CSS Integration','Styled-components with SSR'],
    'Image & Font Optimization':        ['next/image & Image Optimization','next/font & Font Loading','Metadata API for SEO'],
    'State Management':                 ['Server State with React Query','Zustand in Next.js','Context API Patterns'],
    'Database Integration':             ['Prisma ORM with Next.js','Drizzle ORM Overview','Edge Runtime & Vercel KV'],
    'Deployment':                       ['Deploying to Vercel','Environment Variables & Secrets','Analyzing Bundle with next/bundle-analyzer'],
    'Testing Next.js':                  ['Jest & React Testing Library Setup','Testing Server Components','Playwright E2E Testing'],
  },

  'Backend Development': {
    'Backend Fundamentals':             ['Client-Server Architecture','HTTP Protocol & Request-Response Cycle','REST vs GraphQL vs gRPC'],
    'API Design':                       ['RESTful Resource Design','HTTP Methods & Status Codes','API Versioning Strategies'],
    'Authentication & Authorization':   ['Sessions vs JWT Authentication','OAuth 2.0 & OpenID Connect','Role-Based Access Control (RBAC)'],
    'Databases':                        ['SQL vs NoSQL Decision Guide','Database Indexing & Query Optimization','Transactions & ACID Properties'],
    'Caching':                          ['Redis Caching Strategies','Cache Invalidation Patterns','CDN & Edge Caching'],
    'Message Queues':                   ['RabbitMQ: Queues & Exchanges','Apache Kafka: Topics & Partitions','Bull Queue with Node.js'],
    'Microservices':                    ['Monolith vs Microservices','Service-to-Service Communication','API Gateway Pattern'],
    'Security':                         ['OWASP Top 10 Vulnerabilities','SQL Injection Prevention','Rate Limiting & Throttling'],
    'Logging & Monitoring':             ['Structured Logging with Winston','Distributed Tracing with OpenTelemetry','Prometheus & Grafana Metrics'],
    'Testing Backend':                  ['Unit Testing Business Logic','Integration Testing APIs','Contract Testing with Pact'],
    'Deployment':                       ['Containerizing with Docker','Kubernetes Deployment Basics','Blue-Green Deployment Strategy'],
    'Scalability':                      ['Horizontal vs Vertical Scaling','Load Balancing Algorithms','Database Sharding & Replication'],
  },

  'Frontend Development': {
    'HTML & Semantics':                 ['Semantic HTML5 Structure','Accessibility Best Practices','SEO-Friendly Markup'],
    'CSS Mastery':                      ['Flexbox Layout Deep Dive','CSS Grid System','CSS Custom Properties & Theming'],
    'JavaScript for UI':                ['DOM Selection & Manipulation','Event Handling & Bubbling','Fetch API & JSON Handling'],
    'Responsive Design':                ['Mobile-First Approach','Media Queries & Fluid Layouts','Responsive Images & Icons'],
    'Component Frameworks':             ['React Fundamentals for UI','Vue.js Basics','Svelte Overview'],
    'Build Tools':                      ['Webpack & Module Bundling','Vite Dev Server & HMR','npm Scripts & Task Automation'],
    'CSS Preprocessors':                ['Sass: Variables & Nesting','PostCSS & Autoprefixer','CSS-in-JS with Emotion'],
    'Performance':                      ['Critical Rendering Path','Lazy Loading Images & Scripts','Core Web Vitals: LCP, FID, CLS'],
    'Testing Frontend':                 ['Unit Testing with Jest','Component Testing with Testing Library','E2E Testing with Playwright'],
    'Version Control':                  ['Git Workflow for Frontend','Feature Branches & PR Reviews','Git Hooks & Lint-staged'],
    'Package Ecosystems':               ['npm vs yarn vs pnpm','Semantic Versioning','Dependency Auditing & Updates'],
    'Deployment':                       ['Deploying to Netlify & Vercel','CI/CD for Frontend Apps','CDN & Asset Optimization'],
  },

  'Full Stack Development': {
    'Full Stack Architecture':          ['MVC Pattern & Separation of Concerns','Monorepo vs Polyrepo Setup','API-First Development'],
    'Frontend Foundations':             ['React Setup & Component Tree','State Management Patterns','CSS Framework Integration'],
    'Backend Foundations':              ['Node.js & Express REST API','Database Schema Design','Authentication Implementation'],
    'Database Design':                  ['Relational Schema Normalization','NoSQL Document Modeling','ORM: Prisma & Sequelize'],
    'API Integration':                  ['Connecting Frontend to Backend API','CORS Configuration','Error Handling End-to-End'],
    'Authentication Full Stack':        ['JWT Flow from Login to Protected Route','Refresh Token Implementation','Social Login with Google OAuth'],
    'File Uploads':                     ['Multipart Form Data Handling','S3 File Storage Integration','Image Processing & Resizing'],
    'Real-time Features':               ['WebSockets with Socket.io','Server-Sent Events','Real-time Notifications'],
    'Testing Full Stack':               ['Backend API Tests','Frontend Component Tests','E2E User Flow Testing'],
    'DevOps for Full Stack':            ['Dockerizing Frontend & Backend','nginx Reverse Proxy Setup','Environment Variables Management'],
    'Deployment':                       ['Deploying Full Stack on VPS','Vercel + Railway Deployment','Domain & SSL Configuration'],
    'Performance & Optimization':       ['Database Query Optimization','Frontend Bundle Optimization','Load Testing with k6'],
  },

  'System Design': {
    'Design Fundamentals':              ['Functional vs Non-Functional Requirements','Back-of-Envelope Estimation','CAP Theorem & BASE vs ACID'],
    'Scalability':                      ['Horizontal vs Vertical Scaling','Stateless vs Stateful Services','Database Read Replicas'],
    'Load Balancing':                   ['Round-Robin & Least-Connections Algorithms','Layer 4 vs Layer 7 Load Balancers','Health Checks & Circuit Breakers'],
    'Caching Systems':                  ['Redis Architecture & Data Structures','Cache-Aside vs Write-Through Patterns','Cache Eviction: LRU, LFU'],
    'Databases at Scale':               ['Database Sharding Strategies','Consistent Hashing','Read-Write Splitting'],
    'Message Queues':                   ['Kafka Architecture: Brokers & Topics','RabbitMQ Exchange Types','Dead Letter Queues & Retry Logic'],
    'Distributed Systems':              ['Two-Phase Commit Protocol','Saga Pattern for Distributed Transactions','Leader Election with Raft'],
    'Content Delivery':                 ['CDN Architecture & Edge Nodes','Anycast Routing','Video Streaming: HLS & DASH'],
    'API Gateway & Service Mesh':       ['API Gateway Responsibilities','Service Discovery: Consul & Etcd','Istio Service Mesh Basics'],
    'Storage Systems':                  ['Object Storage: S3 Architecture','Block vs File vs Object Storage','Data Lake vs Data Warehouse'],
    'Monitoring & Observability':       ['The Three Pillars: Logs, Metrics, Traces','Distributed Tracing with Jaeger','SLO, SLA & Error Budgets'],
    'Case Studies':                     ['Design Twitter/X Feed System','Design URL Shortener','Design Distributed Cache'],
  },

  'DevOps Engineer': {
    'DevOps Culture':                   ['DevOps Principles & CALMS Framework','DevOps vs SRE Roles','Measuring DevOps with DORA Metrics'],
    'Linux Administration':             ['Linux File System & Permissions','Process Management: ps, top, kill','Shell Scripting: bash Automation'],
    'Version Control & Git':            ['Git Branching Strategies: GitFlow','Trunk-Based Development','Merge Conflicts & Rebasing'],
    'CI/CD Pipelines':                  ['Jenkins Pipeline as Code','GitHub Actions Workflow YAML','GitLab CI/CD Configuration'],
    'Containerization':                 ['Docker Architecture & Images','Writing Efficient Dockerfiles','Docker Compose Multi-Service'],
    'Container Orchestration':          ['Kubernetes Core Objects: Pods, Services','kubectl CLI Commands','Helm Charts & Package Management'],
    'Infrastructure as Code':           ['Terraform: Providers & State','Ansible Playbooks & Roles','Pulumi Overview'],
    'Cloud Platforms':                  ['AWS Core Services for DevOps','Azure DevOps Overview','GCP Cloud Build & Artifact Registry'],
    'Monitoring & Alerting':            ['Prometheus Metrics & PromQL','Grafana Dashboard Creation','Alert Manager & PagerDuty'],
    'Security in DevOps':               ['SAST & DAST Scanning','Secrets Management: Vault','Container Image Scanning with Trivy'],
    'Logging':                          ['ELK Stack: Elasticsearch, Logstash, Kibana','Fluentd & Fluentbit','Log Aggregation Patterns'],
    'SRE Practices':                    ['SLO & Error Budget Policy','Chaos Engineering with Chaos Monkey','Runbooks & Incident Response'],
  },

  'Docker Containers': {
    'Docker Fundamentals':              ['Docker Architecture: Engine, Daemon, CLI','Installing Docker Desktop','Container vs Virtual Machine'],
    'Docker Images':                    ['Pulling Images from Docker Hub','Dockerfile Instructions: FROM, RUN, COPY','Layer Caching & Image Optimization'],
    'Docker Containers':                ['Running Containers: docker run Flags','Container Lifecycle: start, stop, rm','Exec into Container: docker exec'],
    'Networking':                       ['Bridge, Host & None Networks','Container Port Mapping','Custom Docker Networks'],
    'Volumes & Storage':                ['Named Volumes & Bind Mounts','tmpfs Mounts','Volume Drivers & NFS'],
    'Docker Compose':                   ['docker-compose.yml Syntax','Multi-Container Applications','depends_on & Health Checks'],
    'Docker Registry':                  ['Docker Hub: Push & Pull','Private Registry with Harbor','Image Tagging & Versioning'],
    'Dockerfile Best Practices':        ['Multi-Stage Builds','Minimizing Image Size','Non-root User in Containers'],
    'Docker Security':                  ['Container Isolation & namespaces','Scanning with docker scan & Trivy','AppArmor & Seccomp Profiles'],
    'Docker in CI/CD':                  ['Docker in GitHub Actions','Building & Pushing in CI','Docker-in-Docker (DinD)'],
    'Monitoring Containers':            ['Docker Stats & Resource Limits','Prometheus + cAdvisor for Docker','Docker Events & Logging Drivers'],
    'Production Docker':                ['Docker Swarm Basics','Deploying to ECS & GCR','Container Health Checks'],
  },

  'Kubernetes Orchestration': {
    'Kubernetes Architecture':          ['Control Plane: API Server, etcd, Scheduler','Worker Nodes: kubelet & kube-proxy','kubectl Setup & kubeconfig'],
    'Pods':                             ['Pod Lifecycle & Restart Policies','Multi-Container Pods & Sidecars','Pod Resource Requests & Limits'],
    'Workloads':                        ['Deployment: Rolling Updates & Rollbacks','StatefulSet for Stateful Apps','DaemonSet & Job/CronJob'],
    'Services & Networking':            ['ClusterIP, NodePort & LoadBalancer Services','Ingress Controller & TLS','NetworkPolicy for Traffic Control'],
    'Configuration':                    ['ConfigMaps & Volume Mounting','Secrets Management in K8s','Environment Variables from ConfigMap'],
    'Storage':                          ['PersistentVolume & PersistentVolumeClaim','StorageClass & Dynamic Provisioning','CSI Drivers'],
    'Helm':                             ['Helm Chart Structure','Installing & Upgrading Releases','Writing Custom Helm Charts'],
    'Scaling':                          ['HorizontalPodAutoscaler (HPA)','VerticalPodAutoscaler (VPA)','Cluster Autoscaler'],
    'Security':                         ['RBAC: Roles & RoleBindings','Pod Security Standards','Network Policies & Service Mesh'],
    'Monitoring':                       ['Prometheus Operator & ServiceMonitor','Grafana in Kubernetes','Loki for Log Aggregation'],
    'CI/CD with K8s':                   ['ArgoCD GitOps Deployment','Flux CD Overview','Tekton Pipelines'],
    'Multi-cluster & Advanced':         ['Namespaces & Resource Quotas','Kubernetes Federation','Operators & Custom Resources (CRDs)'],
  },

  'AWS Cloud Architect': {
    'AWS Fundamentals':                 ['AWS Global Infrastructure: Regions & AZs','IAM: Users, Groups, Roles & Policies','AWS CLI Setup & Configuration'],
    'Compute':                          ['EC2: Instance Types & AMIs','Auto Scaling Groups & Launch Templates','Lambda Functions & Event Triggers'],
    'Networking':                       ['VPC: Subnets, Route Tables & Gateways','Security Groups vs NACLs','VPC Peering & Transit Gateway'],
    'Storage':                          ['S3: Buckets, Objects & Storage Classes','EBS Volume Types & Snapshots','EFS vs EBS vs S3 Comparison'],
    'Databases':                        ['RDS: Multi-AZ & Read Replicas','DynamoDB: Partitions & GSIs','ElastiCache: Redis & Memcached'],
    'Containers on AWS':                ['ECS: Task Definitions & Services','EKS Managed Node Groups','ECR: Container Registry'],
    'Serverless':                       ['API Gateway + Lambda REST API','Step Functions State Machines','EventBridge Rules & Patterns'],
    'Monitoring & Logging':             ['CloudWatch Metrics & Alarms','CloudTrail Audit Logging','AWS X-Ray Distributed Tracing'],
    'Security & Compliance':            ['KMS: Key Management','AWS Secrets Manager','WAF & Shield DDoS Protection'],
    'DevOps on AWS':                    ['CodePipeline CI/CD','CodeBuild & CodeDeploy','CloudFormation & CDK'],
    'Cost Optimization':                ['AWS Cost Explorer & Budgets','Reserved Instances vs Savings Plans','Trusted Advisor Recommendations'],
    'Architecture Patterns':            ['Well-Architected Framework Pillars','Event-Driven Architecture on AWS','Multi-Account Strategy with AWS Organizations'],
  },

  'Azure Cloud Engineer': {
    'Azure Fundamentals':               ['Azure Portal & Resource Groups','Azure AD: Users, Groups & App Registrations','Azure CLI & PowerShell'],
    'Compute':                          ['Azure Virtual Machines & Scale Sets','Azure App Service Plans','Azure Functions & Durable Functions'],
    'Networking':                       ['Azure Virtual Network & Subnets','NSG & Azure Firewall','ExpressRoute & VPN Gateway'],
    'Storage':                          ['Azure Blob Storage & Access Tiers','Azure Files & File Sync','Managed Disks & Disk Types'],
    'Databases':                        ['Azure SQL Database & Elastic Pools','Cosmos DB: APIs & Partitioning','Azure Cache for Redis'],
    'Containers':                       ['Azure Container Instances (ACI)','AKS: Azure Kubernetes Service','Azure Container Registry (ACR)'],
    'Identity & Security':              ['Managed Identities','Azure Key Vault Secrets & Certificates','Microsoft Defender for Cloud'],
    'DevOps':                           ['Azure DevOps Pipelines (YAML)','Azure Repos & Branch Policies','Azure Artifacts & Package Feeds'],
    'Monitoring':                       ['Azure Monitor & Log Analytics','Application Insights','Azure Alerts & Action Groups'],
    'Serverless':                       ['Logic Apps: Workflow Automation','Azure Event Grid & Event Hubs','Service Bus Queues & Topics'],
    'Cost Management':                  ['Azure Cost Management & Budgets','Azure Reserved Instances','Tagging Strategy for Cost Allocation'],
    'Architecture':                     ['Azure Well-Architected Framework','Hub-Spoke Network Topology','Azure Landing Zones'],
  },

  'GCP Cloud Engineer': {
    'GCP Fundamentals':                 ['GCP Project Structure & Hierarchy','IAM: Roles, Policies & Service Accounts','gcloud CLI Setup'],
    'Compute Engine':                   ['VM Instance Types & Custom Machine Types','Instance Templates & Managed Instance Groups','Preemptible VMs & Spot VMs'],
    'Kubernetes Engine':                ['GKE Cluster Creation & Node Pools','GKE Autopilot Mode','Cloud Build with GKE'],
    'Cloud Run & Functions':            ['Cloud Run: Stateless Containers','Cloud Functions Triggers','App Engine Standard vs Flexible'],
    'Networking':                       ['VPC Networks & Firewall Rules','Cloud Load Balancing Types','Cloud DNS & Cloud Armor'],
    'Storage':                          ['Cloud Storage: Buckets & Object Lifecycle','Persistent Disks & Filestore','Cloud Storage Transfer Service'],
    'Databases':                        ['Cloud SQL: High Availability','Firestore: Document Database','Bigtable vs Spanner Comparison'],
    'Data & Analytics':                 ['BigQuery: Datasets & Queries','Dataflow for Stream & Batch Processing','Pub/Sub Messaging'],
    'AI & ML Services':                 ['Vertex AI: Model Training & Serving','Vision API & Natural Language API','AutoML Overview'],
    'Security':                         ['Cloud KMS & Secret Manager','VPC Service Controls','Security Command Center'],
    'DevOps on GCP':                    ['Cloud Build CI/CD Pipelines','Artifact Registry','Deployment Manager vs Terraform'],
    'Monitoring':                       ['Cloud Monitoring & Uptime Checks','Cloud Logging & Log Sinks','Error Reporting & Profiler'],
  },

  'Cybersecurity Analyst': {
    'Security Fundamentals':            ['CIA Triad: Confidentiality, Integrity, Availability','Security Frameworks: NIST, ISO 27001','Threat Modeling with STRIDE'],
    'Network Security':                 ['TCP/IP Protocol Stack','Firewalls & IDS/IPS Systems','VPN & Network Segmentation'],
    'Cryptography':                     ['Symmetric vs Asymmetric Encryption','TLS/SSL Handshake Process','Hashing: SHA-256 & bcrypt'],
    'Web Application Security':         ['OWASP Top 10 Vulnerabilities','SQL Injection Attack & Defense','XSS & CSRF Attacks'],
    'Ethical Hacking':                  ['Penetration Testing Methodology','Reconnaissance with nmap & Shodan','Exploitation with Metasploit'],
    'Malware Analysis':                 ['Types of Malware: Virus, Worm, Ransomware','Static vs Dynamic Analysis','Sandbox Analysis with Cuckoo'],
    'Incident Response':                ['Incident Response Life Cycle','Digital Forensics Basics','Chain of Custody'],
    'Identity & Access Management':     ['MFA & Password Policies','Zero Trust Architecture','PAM: Privileged Access Management'],
    'Cloud Security':                   ['Shared Responsibility Model','Cloud Security Posture Management','Container Security Scanning'],
    'Security Operations':              ['SIEM: Splunk & Elastic SIEM','Log Analysis & Correlation Rules','Threat Intelligence Feeds'],
    'Compliance & Governance':          ['GDPR & Data Privacy Laws','PCI-DSS for Payment Systems','SOC 2 Type II Reports'],
    'Secure Development':               ['DevSecOps Integration','SAST & DAST Tools','Dependency Vulnerability Scanning'],
  },

  'Machine Learning': {
    'ML Foundations':                   ['Supervised vs Unsupervised vs Reinforcement Learning','Train/Validation/Test Split','Bias-Variance Tradeoff'],
    'Data Preprocessing':               ['Handling Missing Data: Imputation','Feature Scaling: Normalization & Standardization','Categorical Encoding: One-Hot & Label'],
    'Linear Models':                    ['Linear Regression: Gradient Descent','Logistic Regression & Decision Boundary','Ridge & Lasso Regularization'],
    'Tree-Based Models':                ['Decision Trees: Gini & Entropy','Random Forest & Feature Importance','Gradient Boosting: XGBoost & LightGBM'],
    'Support Vector Machines':          ['SVM: Hyperplane & Margin','Kernel Trick: RBF & Polynomial','SVM for Multi-class Classification'],
    'Neural Networks':                  ['Perceptron & Activation Functions','Backpropagation & Gradient Flow','Keras Sequential API'],
    'Deep Learning':                    ['CNN: Convolutional & Pooling Layers','RNN & LSTM for Sequences','Transfer Learning with ResNet'],
    'Unsupervised Learning':            ['K-Means Clustering','PCA: Principal Component Analysis','DBSCAN & Hierarchical Clustering'],
    'Model Evaluation':                 ['Classification Metrics: Precision, Recall, F1','ROC Curve & AUC','Cross-Validation Strategies'],
    'Feature Engineering':              ['Feature Selection Methods','Polynomial Features & Interaction Terms','Text Features with TF-IDF'],
    'ML Pipelines':                     ['Scikit-learn Pipeline API','Hyperparameter Tuning: Grid Search, Optuna','MLflow Experiment Tracking'],
    'ML Deployment':                    ['Exporting Models: pickle & joblib','FastAPI ML Model Serving','Docker + Kubernetes for ML Inference'],
  },

  'Data Science': {
    'Data Science Workflow':            ['CRISP-DM Methodology','Jupyter Notebook Best Practices','Data Science Project Structure'],
    'Python for Data Science':          ['NumPy: Arrays & Broadcasting','Pandas: DataFrames & Series','Matplotlib & Seaborn Basics'],
    'Exploratory Data Analysis':        ['Descriptive Statistics','Univariate & Bivariate Analysis','Outlier Detection Methods'],
    'Data Cleaning':                    ['Handling Duplicates & Inconsistencies','Datetime Parsing & Timezone Handling','String Cleaning with Regex'],
    'Statistical Analysis':             ['Hypothesis Testing: t-test, ANOVA','Correlation vs Causation','A/B Testing Design'],
    'Machine Learning Basics':          ['Scikit-learn Workflow','Classification Algorithms Overview','Regression Algorithms Overview'],
    'Data Visualization':               ['Plotly Interactive Charts','Seaborn Statistical Plots','Dashboard with Streamlit'],
    'Natural Language Processing':      ['Text Preprocessing: Tokenization, Stop Words','TF-IDF Vectorization','Sentiment Analysis with VADER'],
    'Time Series Analysis':             ['Time Series Decomposition','ARIMA & SARIMA Models','Prophet for Forecasting'],
    'Big Data Tools':                   ['PySpark: DataFrames & SQL','Hadoop Ecosystem Overview','Dask for Parallel Computing'],
    'SQL for Data Science':             ['Window Functions for Analytics','CTEs & Recursive Queries','Analytical SQL Patterns'],
    'Reporting & Communication':        ['Storytelling with Data','Building Data Reports in Notion','Dashboards with Tableau/Power BI'],
  },

  'Data Engineering': {
    'Data Engineering Fundamentals':    ['Role of Data Engineer vs Data Scientist','ETL vs ELT Paradigms','Data Pipeline Architecture'],
    'SQL & Databases':                  ['Advanced SQL: Window Functions & CTEs','Database Indexing & Query Plans','OLAP vs OLTP Systems'],
    'Python for Data Engineering':      ['Pandas for ETL Pipelines','PySpark Transformations','Great Expectations for Data Quality'],
    'Data Warehousing':                 ['Star Schema & Snowflake Schema','Dimensional Modeling','Data Mart vs Data Warehouse'],
    'Apache Spark':                     ['Spark Architecture: Driver & Executors','RDDs, DataFrames & Datasets','Spark SQL & Catalyst Optimizer'],
    'Apache Kafka':                     ['Kafka Producers & Consumers','Kafka Topics, Partitions & Offsets','Kafka Streams & ksqlDB'],
    'Airflow & Orchestration':          ['DAG Definition in Airflow','Airflow Operators & Sensors','Scheduling & Dependency Management'],
    'Cloud Data Platforms':             ['Snowflake: Virtual Warehouses','BigQuery: Slots & Reservations','AWS Redshift Architecture'],
    'dbt (Data Build Tool)':            ['dbt Models & ref() Function','dbt Tests & Documentation','dbt Snapshots & Incremental Models'],
    'Data Lake & Lakehouse':            ['Delta Lake ACID Transactions','Apache Iceberg Table Format','Data Lake vs Data Lakehouse'],
    'Data Quality & Governance':        ['Data Lineage Tracking','Data Catalog with Apache Atlas','Schema Registry & Evolution'],
    'Streaming Pipelines':              ['Flink Stream Processing','Kafka Connect Connectors','Real-time Dashboard with ClickHouse'],
  },

  'AI Engineer': {
    'AI Engineering Fundamentals':      ['AI vs ML vs Deep Learning Distinctions','AI Engineering Workflow','Python AI Tooling Ecosystem'],
    'Prompt Engineering':               ['Zero-shot & Few-shot Prompting','Chain-of-Thought Prompting','System Prompts & Role Instructions'],
    'LLM Architecture':                 ['Transformer Architecture Deep Dive','Attention Mechanism & Self-Attention','Tokenization & Embeddings'],
    'Fine-tuning LLMs':                 ['Fine-tuning vs Prompt Engineering','LoRA & QLoRA Parameter-Efficient Fine-tuning','Preparing Training Datasets'],
    'RAG Systems':                      ['Retrieval-Augmented Generation Pipeline','Vector Databases: Pinecone & Weaviate','Chunking & Embedding Strategies'],
    'LangChain Framework':              ['LangChain Chains & Runnables','Agents & Tools in LangChain','Memory: Buffer & Vector Memory'],
    'AI APIs':                          ['OpenAI API: Chat Completions & Embeddings','Anthropic Claude API','Hugging Face Inference API'],
    'Vector Databases':                 ['Embedding Search with FAISS','Qdrant Setup & Collections','ChromaDB for Local RAG'],
    'AI Application Development':       ['Building Chatbots with Streaming','Document Q&A Systems','AI-Powered Search'],
    'Evaluation & Testing':             ['LLM Evaluation Metrics: BLEU, ROUGE, RAGAS','Hallucination Detection','Red Teaming LLMs'],
    'MLOps for AI':                     ['Model Versioning with MLflow','Deployment: vLLM & Ollama','Monitoring LLM Applications'],
    'AI Safety & Ethics':               ['Bias in AI Systems','Responsible AI Principles','GDPR Compliance for AI'],
  },

  'Artificial Intelligence': {
    'AI Foundations':                   ['History & Milestones of AI','Intelligent Agents & Environments','Problem Formulation in AI'],
    'Search Algorithms':                ['Breadth-First & Depth-First Search','A* Search Algorithm','Heuristic Functions & Admissibility'],
    'Knowledge Representation':         ['Propositional Logic','First-Order Predicate Logic','Ontologies & Knowledge Graphs'],
    'Machine Learning Overview':        ['Supervised Learning Algorithms','Unsupervised Learning Methods','Reinforcement Learning Basics'],
    'Neural Networks':                  ['Feedforward Networks & Activation Functions','Backpropagation Mathematics','Regularization: Dropout & Batch Norm'],
    'Deep Learning':                    ['Convolutional Neural Networks (CNN)','Recurrent Neural Networks (RNN)','Transformer Architecture'],
    'Natural Language Processing':      ['Tokenization & Text Preprocessing','Word Embeddings: Word2Vec & GloVe','BERT & GPT Overview'],
    'Computer Vision':                  ['Image Classification with CNN','Object Detection: YOLO & Faster RCNN','Image Segmentation Overview'],
    'Reinforcement Learning':           ['Markov Decision Processes','Q-Learning & DQN','Policy Gradient Methods'],
    'Planning & Reasoning':             ['Classical Planning: STRIPS','Monte Carlo Tree Search','Bayesian Reasoning & Belief Networks'],
    'AI Ethics & Safety':               ['Algorithmic Bias & Fairness','Explainable AI (XAI)','AI Governance & Regulations'],
    'AI Applications':                  ['Recommendation Systems','Autonomous Vehicles AI','AI in Healthcare & Drug Discovery'],
  },

  'Blockchain Developer': {
    'Blockchain Fundamentals':          ['Distributed Ledger Technology','Cryptographic Hash Functions in Blockchain','Consensus Mechanisms: PoW & PoS'],
    'Bitcoin & Ethereum':               ['Bitcoin UTXO Model','Ethereum Accounts & State','Gas & Transaction Fees'],
    'Solidity Programming':             ['Solidity Data Types & Variables','Functions, Modifiers & Events','Inheritance & Interfaces in Solidity'],
    'Smart Contracts':                  ['Writing & Deploying Smart Contracts','Contract ABI & Bytecode','Smart Contract Security Patterns'],
    'DeFi Development':                 ['ERC-20 Token Standard','Uniswap AMM Mechanism','Lending Protocols: Aave & Compound'],
    'NFTs & ERC-721':                   ['ERC-721 NFT Standard','NFT Metadata & IPFS Storage','NFT Marketplace Architecture'],
    'Web3.js & Ethers.js':              ['Connecting to Ethereum with ethers.js','Reading Contract State','Sending Transactions from Frontend'],
    'Hardhat Development':              ['Hardhat Setup & Configuration','Writing & Running Tests','Hardhat Network & Forking'],
    'IPFS & Decentralized Storage':     ['IPFS Content Addressing','Pinning Services: Pinata & Infura','Filecoin & Arweave Overview'],
    'Layer 2 Solutions':                ['Optimistic Rollups: Optimism & Arbitrum','ZK Rollups & zkSync','Polygon Architecture'],
    'Smart Contract Security':          ['Reentrancy Attack & Fix','Integer Overflow & SafeMath','Audit Process & Tools: Slither'],
    'Blockchain DevOps':                ['CI/CD for Smart Contracts','Multi-Signature Wallets','Contract Upgradability Patterns'],
  },

  'Android Developer': {
    'Android Fundamentals':             ['Android Studio Setup & Project Structure','Activity Lifecycle','Manifest File & Permissions'],
    'Kotlin for Android':               ['Kotlin Basics: Variables & Functions','Kotlin Coroutines Basics','Extension Functions & Lambdas'],
    'UI with Jetpack Compose':          ['Composable Functions & Recomposition','Layouts: Column, Row & Box','State in Compose: remember & mutableStateOf'],
    'Navigation':                       ['Jetpack Navigation Component','Navigation Graph & Destinations','Passing Arguments Between Screens'],
    'ViewModel & LiveData':             ['ViewModel Scope & Factory','LiveData Observers','StateFlow & SharedFlow'],
    'Networking':                       ['Retrofit Setup & API Interface','OkHttp Interceptors','Kotlin Serialization & Gson'],
    'Local Storage':                    ['Room Database: Entity, DAO & Database','SharedPreferences & DataStore','File Storage & Content Providers'],
    'Dependency Injection':             ['Hilt Setup & Application','Hilt in ViewModels','Module Providers & Binds'],
    'Background Work':                  ['WorkManager for Deferrable Work','ForegroundService for Long Tasks','AlarmManager & Broadcast Receivers'],
    'Testing Android':                  ['JUnit4 & Mockito for Unit Tests','Espresso UI Testing','Robolectric for Isolated Tests'],
    'Publishing':                       ['Signing APK & App Bundle (AAB)','Play Console Setup','App Permissions Best Practices'],
    'Advanced Android':                 ['Custom Views & Canvas Drawing','App Performance Profiling','Deep Links & App Links'],
  },

  'Flutter Developer': {
    'Flutter Fundamentals':             ['Flutter Architecture & Dart Basics','Widget Tree & Element Tree','Hot Reload & Hot Restart'],
    'Core Widgets':                     ['StatelessWidget vs StatefulWidget','Container, Row, Column & Stack','ListView & GridView'],
    'Styling & Theming':                ['ThemeData & ColorScheme','Custom Fonts & TextStyles','Responsive UI with MediaQuery'],
    'State Management':                 ['Provider Package','Riverpod State Management','BLoC Pattern & Cubit'],
    'Navigation':                       ['Navigator 1.0 & 2.0','go_router Package','Deep Linking in Flutter'],
    'Networking':                       ['http & dio Packages','JSON Serialization with json_serializable','Interceptors & API Error Handling'],
    'Local Storage':                    ['shared_preferences Package','sqflite: SQLite in Flutter','Hive NoSQL Database'],
    'Firebase Integration':             ['Firebase Auth: Email & Google Login','Firestore CRUD Operations','Firebase Storage & Push Notifications'],
    'Animations':                       ['Implicit Animations: AnimatedContainer','Explicit Animations: AnimationController','Hero Animations & Page Transitions'],
    'Platform Channels':                ['Method Channels for Native Code','Platform-Specific Plugins','Writing Custom Flutter Plugins'],
    'Testing Flutter':                  ['Unit Testing with flutter_test','Widget Testing with testWidgets','Integration Testing with patrol'],
    'Deployment':                       ['Building APK & IPA Files','Publishing to Google Play','Publishing to Apple App Store'],
  },

  'SQL & Databases': {
    'SQL Fundamentals':                 ['SELECT, FROM & WHERE Clauses','ORDER BY, LIMIT & OFFSET','Filtering with AND, OR & NOT'],
    'Data Manipulation':                ['INSERT, UPDATE & DELETE Statements','UPSERT & INSERT ON DUPLICATE KEY','Transactions: BEGIN, COMMIT, ROLLBACK'],
    'Joins':                            ['INNER JOIN & Implicit Join','LEFT, RIGHT & FULL OUTER JOIN','SELF JOIN & CROSS JOIN'],
    'Aggregation':                      ['GROUP BY & HAVING Clauses','Aggregate Functions: COUNT, SUM, AVG, MIN, MAX','DISTINCT & COUNT DISTINCT'],
    'Subqueries':                       ['Correlated vs Non-Correlated Subqueries','EXISTS & NOT EXISTS','Subqueries in SELECT & FROM Clauses'],
    'Window Functions':                 ['ROW_NUMBER, RANK & DENSE_RANK','LEAD, LAG, FIRST_VALUE & LAST_VALUE','PARTITION BY with Window Functions'],
    'CTEs & Views':                     ['Common Table Expressions (WITH Clause)','Recursive CTEs','Creating & Managing Views'],
    'Indexing':                         ['B-Tree Index Internals','Composite & Covering Indexes','EXPLAIN ANALYZE & Query Plans'],
    'Schema Design':                    ['Normalization: 1NF, 2NF, 3NF','ER Diagrams & Relationships','Foreign Keys & Referential Integrity'],
    'Stored Procedures & Functions':    ['Creating Stored Procedures','User-Defined Functions','Triggers & Events'],
    'PostgreSQL Features':              ['JSONB Data Type & Operators','Array Columns & Functions','Full-Text Search with tsvector'],
    'Database Administration':          ['User Roles & Privileges','Backup & Restore with pg_dump','Replication & High Availability'],
  },

  'Data Structures & Algorithms': {
    'Arrays & Strings':                 ['Array Operations & Time Complexity','Two-Pointer Technique','Sliding Window Pattern'],
    'Linked Lists':                     ['Singly Linked List Operations','Doubly Linked List','Floyd Cycle Detection Algorithm'],
    'Stacks & Queues':                  ['Stack: Push, Pop & Applications','Queue & Deque Operations','Monotonic Stack Pattern'],
    'Trees':                            ['Binary Tree Traversals: Inorder, Preorder, Postorder','Binary Search Tree Operations','AVL Trees & Rotations'],
    'Heaps':                            ['Min-Heap & Max-Heap','Heap Sort Algorithm','Priority Queue Applications'],
    'Hash Tables':                      ['Hash Functions & Collision Resolution','HashMap & HashSet Operations','Two-Sum & Frequency Count Patterns'],
    'Graphs':                           ['Graph Representation: Adjacency List & Matrix','BFS & DFS Graph Traversal','Dijkstra Shortest Path Algorithm'],
    'Sorting Algorithms':               ['Merge Sort & Time Complexity O(n log n)','Quick Sort & Partition Schemes','Counting Sort & Radix Sort'],
    'Recursion & Backtracking':         ['Recursive Problem Decomposition','Backtracking Template: N-Queens','Memoization vs Tabulation'],
    'Dynamic Programming':              ['DP Fundamentals: Optimal Substructure','Knapsack Problem Variants','Longest Common Subsequence'],
    'Greedy Algorithms':                ['Activity Selection Problem','Huffman Coding','Kruskal & Prim Minimum Spanning Tree'],
    'Advanced Topics':                  ['Trie Data Structure','Segment Tree & Fenwick Tree','Union-Find / Disjoint Set Union'],
  },

  'Competitive Programming': {
    'CP Fundamentals':                  ['Competitive Programming Environment Setup','Complexity Analysis: Big-O Mastery','STL for Competitive Programming'],
    'Number Theory':                    ['Sieve of Eratosthenes','Modular Arithmetic & Modular Inverse','GCD, LCM & Extended Euclidean'],
    'Bit Manipulation':                 ['Bitwise Operators in CP','Bitmask DP Patterns','XOR Tricks & Applications'],
    'String Algorithms':                ['KMP String Matching','Z-Algorithm for Pattern Search','Manacher Palindrome Algorithm'],
    'Graph Algorithms':                 ['Bellman-Ford Algorithm','Floyd-Warshall All-Pairs Shortest Path','Topological Sort: Kahn & DFS'],
    'Advanced Graph':                   ["Tarjan's SCC Algorithm","Articulation Points & Bridges","Kosaraju's Algorithm"],
    'Dynamic Programming':              ['DP on Trees','DP on DAGs','DP Optimization: Convex Hull Trick'],
    'Segment Trees':                    ['Point Update & Range Query','Lazy Propagation','Persistent Segment Tree'],
    'Geometry':                         ['Convex Hull: Graham Scan','Line Intersection','Polygon Area & Pick Theorem'],
    'Game Theory':                      ['Sprague-Grundy Theorem','Nim Game Analysis','Game DP Problems'],
    'Combinatorics':                    ['Permutations & Combinations','Catalan Numbers','Inclusion-Exclusion Principle'],
    'Advanced Data Structures':         ['Trie with XOR DP','Sqrt Decomposition','Heavy-Light Decomposition'],
  },

  'Placement Preparation': {
    'Resume & Applications':            ['Writing an ATS-Friendly Resume','Crafting a Strong Cover Letter','LinkedIn Profile Optimization'],
    'DSA for Interviews':               ['Top 50 LeetCode Pattern Problems','Array & String Interview Patterns','Tree & Graph Interview Problems'],
    'System Design Interviews':         ['How to Approach System Design','Designing a URL Shortener','Designing a Notification System'],
    'Behavioral Interviews':            ['STAR Method for Behavioral Questions','Top 10 Behavioral Questions Answered','Negotiating Salary & Offers'],
    'HR Interview Prep':                ['Tell Me About Yourself – Formula','Why Do You Want to Work Here?','Where Do You See Yourself in 5 Years?'],
    'OOP Concepts':                     ['SOLID Principles Explained','Design Patterns: Singleton, Factory, Observer','OOP Interview Questions'],
    'Database Interviews':              ['SQL Joins & Subquery Interview Questions','Database Design Interview Scenarios','Transaction & Index Interview Questions'],
    'OS Concepts':                      ['Processes vs Threads','Deadlock Detection & Prevention','Memory Management: Paging & Segmentation'],
    'Networking Concepts':              ['TCP vs UDP & OSI Model','HTTP/HTTPS & TLS Handshake','DNS Resolution & CDNs'],
    'Company-Specific Prep':            ['FAANG Interview Process Overview','Product vs Service Company Differences','Startup Interview Expectations'],
    'Mock Interviews':                  ['How to Structure Your Answers','Time Management in Coding Rounds','Virtual Whiteboard Techniques'],
    'Offer & Negotiation':              ['Evaluating Job Offers','Equity & Stock Options Basics','Negotiation Scripts & Tactics'],
  },

  'UI/UX Design': {
    'Design Fundamentals':              ['Elements of Design: Color, Typography, Space','Design Principles: Contrast, Alignment, Repetition','Gestalt Principles in UI'],
    'User Research':                    ['User Interviews & Contextual Inquiry','Surveys & Usability Testing','Affinity Mapping & Personas'],
    'Information Architecture':         ['Card Sorting Technique','Sitemap & Navigation Design','Content Hierarchy Principles'],
    'Wireframing':                      ['Low-Fidelity Wireframes','Wireframing Tools: Balsamiq & Whimsical','Wireframe to Prototype Flow'],
    'Figma Mastery':                    ['Figma Components & Variants','Auto Layout in Figma','Prototyping & Interaction Design'],
    'Visual Design':                    ['Typography Systems & Type Scale','Color Theory & Accessible Palettes','Grid Systems & Spacing'],
    'Interaction Design':               ['Micro-interactions & Feedback','Animation Principles for UI','Gestural Interfaces & Touch Targets'],
    'Accessibility':                    ['WCAG 2.1 Guidelines','Color Contrast & Screen Readers','Keyboard Navigation UX'],
    'Design Systems':                   ['Building a Component Library','Design Tokens & Variables','Storybook for Design Systems'],
    'Responsive Design':                ['Mobile-First Design Approach','Adaptive vs Responsive Design','Breakpoints & Fluid Grids'],
    'User Testing':                     ['Usability Test Planning','Heuristic Evaluation Method','A/B Testing in Product Design'],
    'Portfolio & Career':               ['Building a UX Portfolio','Case Study Structure','UX Design Interview Preparation'],
  },

  'Web Development': {
    'How the Web Works':                ['DNS Resolution & Domain Names','HTTP/HTTPS Protocol','Client-Server Request-Response Cycle'],
    'HTML Foundations':                 ['HTML Document Structure','Semantic HTML5 Elements','Forms & Input Validation'],
    'CSS Fundamentals':                 ['Selectors, Properties & Cascade','Flexbox Layout System','CSS Grid Layout'],
    'JavaScript Basics':                ['Variables, Data Types & Operators','Functions & Control Flow','DOM Manipulation Basics'],
    'Responsive Web':                   ['Media Queries & Breakpoints','Mobile-First Design','Viewport & rem Units'],
    'Frontend Frameworks':              ['React Component Basics','Vue.js Directives & Reactivity','Svelte Reactive Statements'],
    'Backend Basics':                   ['Node.js & Express Setup','REST API Creation','Database with MongoDB Atlas'],
    'Version Control':                  ['Git Init, Add & Commit','GitHub: Push, Pull & Clone','Branching & Merging'],
    'Deployment':                       ['Deploying Static Sites to Netlify','Deploying Node.js to Railway','Environment Variables & Secrets'],
    'Web Security':                     ['HTTPS & SSL Certificates','XSS & CSRF Prevention','Content Security Policy'],
    'Performance':                      ['Minification & Bundling','Image Optimization Techniques','Lighthouse Audit & Core Web Vitals'],
    'Modern Tooling':                   ['npm & package.json','Webpack & Vite Bundlers','ESLint & Prettier Setup'],
  },
};

module.exports = CURRICULUM_MAP;
