// ============================================================
// backend/resetStaleLessons.js
// EduNet Lesson Pipeline Reset Utility
//
// PURPOSE: Identifies all lessons that do NOT match handcrafted
// templates and resets their cached learning_notes, forcing
// regeneration with the new composed curriculum engine.
// ============================================================
'use strict';

require('dotenv').config();
const db = require('./config/db');

// Exact matching logic copied from lessonAssembler.js target checks
function isHandcrafted(title, moduleTitle) {
  const modTitle = String(moduleTitle || '').toLowerCase();
  const lesTitle = String(title || '').toLowerCase();
  const target = `${modTitle} : ${lesTitle}`;

  if (target.includes('python introduction') || target.includes('setup') || target.includes('introduction')) {
    if (modTitle.includes('python introduction')) return true;
  }
  
  if (target.includes('rest api') || target.includes('api') || target.includes('express api')) {
    if (lesTitle.includes('setup') || lesTitle.includes('introduction') || lesTitle.includes('rest api')) {
      if (modTitle.includes('rest api') || modTitle.includes('express api') || modTitle.includes('api')) return true;
    }
  }
  
  if (target.includes('json')) return true;
  if (target.includes('http')) return true;
  if (target.includes('sql join') || target.includes('join')) return true;
  if (target.includes('constant')) return true;
  if (target.includes('variable') || lesTitle.includes('variables')) return true;
  
  if (lesTitle.includes('if statement') || lesTitle.includes('conditional') || lesTitle.includes('if') || lesTitle.includes('control flow') || lesTitle.includes('logic')) return true;
  if (lesTitle.includes('loop') || lesTitle.includes('iteration') || lesTitle.includes('repeat')) return true;
  if (lesTitle.includes('function') || lesTitle.includes('func') || lesTitle.includes('method')) return true;
  if (lesTitle.includes('array') || lesTitle.includes('list')) return true;
  if (lesTitle.includes('class') || lesTitle.includes('inheritance') || lesTitle.includes('polymorphism')) return true;
  if (lesTitle.includes('object') || lesTitle.includes('oop') || lesTitle.includes('abstraction') || lesTitle.includes('encapsulation')) return true;

  return false;
}

async function resetStale() {
  console.log('====================================================');
  console.log(' EduNet Database Lessons Cache Reset Utility');
  console.log('====================================================\n');

  // Load all lessons with module titles
  const [lessons] = await db.query(`
    SELECT ml.id, ml.title, ml.learning_notes, rm.title AS module_title
    FROM module_lessons ml
    JOIN roadmap_modules rm ON ml.module_id = rm.id
    ORDER BY ml.id ASC
  `);

  console.log(`📊 Total lessons: ${lessons.length}`);
  
  let handcraftedCount = 0;
  let resetCount = 0;
  
  for (const lesson of lessons) {
    if (isHandcrafted(lesson.title, lesson.module_title)) {
      handcraftedCount++;
      // Keep handcrafted content intact
      continue;
    }

    // This is a dynamically generated lesson with stale/incorrect variables fallback.
    // Reset its cached learning_notes so it gets regenerated by the new composer.
    await db.query(
      `UPDATE module_lessons SET learning_notes = '' WHERE id = ?`,
      [lesson.id]
    );
    resetCount++;
  }

  console.log(`\n✅ Reset completed successfully!`);
  console.log(`   - Handcrafted lessons preserved: ${handcraftedCount}`);
  console.log(`   - Stale fallback lessons reset : ${resetCount}`);
  console.log('====================================================\n');
  
  process.exit(0);
}

resetStale().catch(err => {
  console.error('FATAL RESET ERROR:', err);
  process.exit(1);
});
