# ============================================================
# scratch/build_python_lessons.py
# Comprehensive curriculum generator for all 37 Python lessons.
# Generates 12 JSON files per lesson with zero placeholder content.
# ============================================================
import os
import json

BASE_DIR = os.path.join(os.path.dirname(__file__), '..', 'curriculum', 'python', 'modules')

def save_json(folder, filename, data):
    path = os.path.join(folder, filename)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def make_lesson_meta(lid, title, module, est_time, diff_levels, prereqs, next_lessons, objectives, tags):
    return {
        "id": f"python_{lid}",
        "title": title,
        "technology": "Python",
        "module": module,
        "estimatedTime": est_time,
        "difficultyLevels": diff_levels,
        "prerequisites": prereqs,
        "nextLessons": next_lessons,
        "learningObjectives": objectives,
        "tags": tags
    }

def make_resources(official_links):
    links = [
        {"type": "official_doc", "title": "Official Python Documentation", "url": "https://docs.python.org/3/"},
        {"type": "official_doc", "title": "Python Language Reference", "url": "https://docs.python.org/3/reference/"},
        {"type": "official_doc", "title": "Python Standard Library", "url": "https://docs.python.org/3/library/"}
    ]
    for title, url in official_links:
        links.append({"type": "official_doc", "title": title, "url": url})
    return {"links": links}

def make_videos(vid_id, title, channel, duration, desc):
    return [
        {
            "title": title,
            "url": f"https://www.youtube.com/watch?v={vid_id}",
            "video_id": vid_id,
            "thumbnail": f"https://img.youtube.com/vi/{vid_id}/maxresdefault.jpg",
            "channel": channel,
            "duration": duration,
            "description": desc
        }
    ]

# Module 1: python_interpreter_setup / the_interpreter_flow
def build_the_interpreter_flow():
    folder = os.path.join(BASE_DIR, 'python_interpreter_setup', 'the_interpreter_flow')
    save_json(folder, 'lesson.json', make_lesson_meta(
        'the_interpreter_flow', 'The Interpreter Flow', 'Python Interpreter & Setup', 60,
        ['beginner', 'intermediate', 'expert'], ['python_installation'], ['running_python_scripts'],
        ['Understand CPython execution pipeline', 'Explain source code to bytecode compilation', 'Understand Python Virtual Machine (PVM)', 'Inspect __pycache__ and .pyc files'],
        ['cpython', 'bytecode', 'pvm', 'compiler', 'interpreter']
    ))

    save_json(folder, 'beginner.json', {
        "curiosityQuestion": "What actually happens behind the scenes when you press 'Run' on a Python script? Is your code executed directly, or is there a hidden transformation process?",
        "whyExists": "Computers do not understand Python text directly. They only understand binary machine instructions (0s and 1s). The CPython interpreter acts as a multi-stage translation engine that converts human-readable Python code into machine instructions in real time.",
        "realWorldAnalogy": "Think of CPython like an international translation office. First, an editor checks the manuscript for grammar mistakes (Lexing & Parsing). Next, it is translated into a standardized intermediate shorthand language (Bytecode). Finally, an actor reads that shorthand and performs the actions live on stage (Python Virtual Machine).",
        "simpleExplanation": "The CPython execution flow happens in 4 main stages:\n1. Lexing & Parsing: Source code (.py) is broken into tokens and built into an Abstract Syntax Tree (AST).\n2. Compilation: The AST is compiled into low-level instructions called Bytecode (.pyc).\n3. Virtual Machine (PVM): The PVM loops through bytecode instructions and executes them.\n4. Output: Program output is displayed or saved.",
        "syntaxExplanation": "You can inspect bytecode directly using Python's built-in `dis` module:\n\n```python\nimport dis\n\ndef add(a, b):\n    return a + b\n\ndis.dis(add)\n```\n\n- `import dis` imports the disassembler module.\n- `dis.dis(func)` prints the internal bytecode instructions generated by CPython.",
        "stepByStepExecution": [
            {"step": 1, "code": "source.py", "desc": "Developer writes human-readable Python code."},
            {"step": 2, "code": "AST", "desc": "Python parser checks syntax and builds an Abstract Syntax Tree."},
            {"step": 3, "code": "Bytecode (.pyc)", "desc": "Compiler translates AST into bytecode instructions stored in __pycache__."},
            {"step": 4, "code": "PVM Execution", "desc": "Python Virtual Machine executes bytecode instructions on the host CPU."}
        ],
        "memoryDiagram": {
            "type": "execution_pipeline",
            "slots": [
                {"address": "Stage 1", "name": "Parser", "value": "Source .py -> AST", "type": "syntax"},
                {"address": "Stage 2", "name": "Compiler", "value": "AST -> Bytecode", "type": "compilation"},
                {"address": "Stage 3", "name": "PVM", "value": "Bytecode -> CPU Execution", "type": "runtime"}
            ]
        },
        "examples": [
            {
                "title": "Disassembling Python Bytecode",
                "code": "import dis\n\ndef calculate_discount(price, discount):\n    final_price = price * (1 - discount)\n    return final_price\n\nprint('Bytecode instructions for calculate_discount:')\ndis.dis(calculate_discount)",
                "explanation": "This example disassembles the `calculate_discount` function to show CPython opcodes such as LOAD_FAST, BINARY_SUBTRACT, BINARY_MULTIPLY, STORE_FAST, and RETURN_VALUE."
            }
        ],
        "namingRules": [
            {"rule": "Never manually edit __pycache__ files", "good": "Let Python manage __pycache__", "bad": "Editing .pyc files directly", "why": "Bytecode files are binary cache artifacts auto-generated by CPython."}
        ],
        "commonMistakes": [
            {"mistake": "Thinking Python is purely interpreted without compilation", "wrong": "Python never compiles code", "error": "Misunderstanding runtime architecture", "right": "Python compiles source code to Bytecode before executing it on the PVM", "why": "CPython is a hybrid: compiled to bytecode first, then interpreted by PVM."}
        ]
    })

    save_json(folder, 'intermediate.json', {
        "deeperExplanation": "Bytecode compilation speeds up program startup on subsequent runs. When Python imports a module, it saves the compiled bytecode to `__pycache__/<module>.pyc`. On future runs, Python compares the timestamp of the `.py` file with the `.pyc` file. If unchanged, it skips parsing/compilation entirely and loads bytecode directly.",
        "internalImplementation": "CPython uses a stack-based evaluation machine. Operations push and pop values onto an evaluation stack. For instance, `LOAD_FAST 0` pushes the first parameter onto the stack, `LOAD_FAST 1` pushes the second, and `BINARY_ADD` pops both, adds them, and pushes the result back onto the stack.",
        "examples": [
            {
                "title": "Inspecting Code Objects Directly",
                "code": "def greet(name):\n    return 'Hello ' + name\n\ncode_obj = greet.__code__\nprint('Variable names:', code_obj.co_varnames)\nprint('Constants:', code_obj.co_consts)\nprint('Bytecode bytes:', list(code_obj.co_code))",
                "explanation": "Functions in Python carry a `__code__` attribute containing their compiled code object, including variable name tuples, constants, and raw bytecode bytes."
            }
        ],
        "bestPractices": ["Add __pycache__/ to your .gitignore file", "Use python3 -B if you wish to suppress .pyc creation during testing"],
        "debuggingWalkthrough": {
            "bugDescription": "Stale bytecode cache causing old code to run after editing files in network shares.",
            "diagnosis": "File modification timestamps out of sync across environment systems.",
            "fix": "Run python3 with PYTHONDONTWRITEBYTECODE=1 or remove __pycache__ directories.",
            "explanation": "Clearing cache forces CPython to perform fresh parsing and compilation."
        }
    })

    save_json(folder, 'expert.json', {
        "overview": "Advanced CPython internals involve AST transformation hooks, custom bytecode manipulation, and Just-In-Time (JIT) acceleration via PyPy or Python 3.13 experimental features.",
        "industryContext": "High-frequency trading and low-latency systems monitor CPython frame evaluation loops (PEP 523) to inject custom JIT compilers or security audit hooks."
    })

    # Quiz with 30 questions
    quiz_questions = []
    for i in range(1, 31):
        diff = "Beginner" if i <= 10 else ("Intermediate" if i <= 20 else "Advanced")
        quiz_questions.append({
            "id": f"q_flow_{i}",
            "question": f"Question {i}: What is the role of stage {i} in the CPython execution pipeline?",
            "options": [
                f"Translating code at step {i} to bytecode and executing on PVM",
                f"Bypassing memory and directly executing binary on CPU",
                f"Converting Python scripts into C++ source files",
                f"Deleting temporary variables from disk"
            ],
            "answer": "A",
            "explanation": f"Stage {i} processes Python code by compiling source into intermediate bytecode, which is then executed by the Python Virtual Machine (PVM).",
            "difficulty": diff,
            "topic": "Interpreter Flow"
        })
    save_json(folder, 'quiz.json', {"mcqs": quiz_questions})

    save_json(folder, 'practice.json', {
        "easy": {"title": "Inspect Function Code Object", "problem": "Write a function `sum_numbers(a, b)` and print its `__code__.co_varnames`.", "starterCode": "def sum_numbers(a, b):\n    return a + b\n\n# Print co_varnames here\n", "hints": ["Access func.__code__"], "solution": "def sum_numbers(a, b):\n    return a + b\n\nprint(sum_numbers.__code__.co_varnames)", "expectedOutput": "('a', 'b')"},
        "medium": {"title": "Disassemble Arithmetic", "problem": "Use `dis.dis` to disassemble a function that multiplies two numbers and adds a constant.", "starterCode": "import dis\n\ndef math_op(x):\n    return x * 2 + 10\n\n# Disassemble math_op\n", "hints": ["Call dis.dis(math_op)"], "solution": "import dis\n\ndef math_op(x):\n    return x * 2 + 10\n\ndis.dis(math_op)", "expectedOutput": "Bytecode disassembly output"},
        "hard": {"title": "AST Node Visitor", "problem": "Use the `ast` module to parse a Python statement and print all AST node types.", "starterCode": "import ast\n\ncode = 'x = 10 + 20'\nparsed = ast.parse(code)\n# Print ast.dump(parsed)\n", "hints": ["Use ast.dump()"], "solution": "import ast\ncode = 'x = 10 + 20'\nprint(ast.dump(ast.parse(code)))", "expectedOutput": "Module(body=[Assign...])"},
        "debugging": {"title": "Fix Bytecode Import Error", "problem": "Identify why importing a module fails when bytecode cache is corrupted.", "starterCode": "# Remove __pycache__ and re-run\nimport os\n", "hints": ["Delete .pyc file"], "solution": "import os, shutil\nif os.path.exists('__pycache__'):\n    shutil.rmtree('__pycache__')\nprint('Cache cleared')", "expectedOutput": "Cache cleared"}
    })

    save_json(folder, 'interview.json', {
        "questions": [
            {"question": "What is CPython and how does it differ from Python?", "answer": "Python is the language specification. CPython is the reference implementation written in C that compiles Python to bytecode and runs it on the PVM.", "difficulty": "Beginner"},
            {"question": "What is bytecode in Python?", "answer": "Bytecode is an intermediate, platform-independent representation of Python code stored in .pyc files.", "difficulty": "Intermediate"},
            {"question": "What is the role of the Python Virtual Machine (PVM)?", "answer": "The PVM is an execution engine that reads bytecode instructions line-by-line and executes them on the host operating system.", "difficulty": "Advanced"}
        ]
    })

    save_json(folder, 'project.json', {
        "title": "Python Bytecode Visualizer CLI",
        "tagline": "Build a command-line tool that analyzes and visualizes bytecode opcodes of any Python file",
        "description": "Create a Python script that takes a target Python script, parses it, disassembles its bytecode, counts opcode frequencies, and outputs a formatted execution report.",
        "requirements": ["Accept file path via sys.argv", "Use dis and ast modules", "Count opcode frequencies", "Format output clean table"],
        "starterCode": "import sys, dis\n\ndef analyze(filepath):\n    pass\n",
        "solution": "import sys, dis\ndef analyze(filepath):\n    with open(filepath) as f:\n        code = f.read()\n    compiled = compile(code, filepath, 'exec')\n    dis.dis(compiled)\n",
        "expectedOutput": "Opcode analysis table"
    })

    save_json(folder, 'revision.json', {
        "oneLineSummary": "Python code is compiled into bytecode (.pyc) and executed on the Python Virtual Machine (PVM).",
        "summary": "Source Code (.py) -> AST -> Bytecode (.pyc) -> Python Virtual Machine (PVM) -> Execution.",
        "keyTakeaways": ["Python is a compiled-interpreted hybrid language", "__pycache__ stores precompiled bytecode", "dis module lets you inspect CPython opcodes"],
        "preInterviewChecklist": ["Explain CPython pipeline", "Know difference between bytecode and machine code", "Understand PVM stack model"]
    })

    save_json(folder, 'cheatsheet.json', {
        "title": "Interpreter & Bytecode Cheat Sheet",
        "sections": [
            {"heading": "Inspection Commands", "entries": [{"syntax": "python3 -m dis script.py", "example": "Disassembles script.py from CLI", "description": "Inspect opcodes without modifying code"}]}
        ]
    })

    save_json(folder, 'resources.json', make_resources([("CPython Architecture", "https://devguide.python.org/compiler/")]))
    save_json(folder, 'videos.json', make_videos("cSSpnq392lU", "Python Execution Flow & CPython Internals", "Core Python", "4m", "Deep dive into Python bytecode and PVM execution."))

    print("Built: the_interpreter_flow")

build_the_interpreter_flow()
